package com.grigorio.rzd.TicketServiceWSProxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://194.186.222.203/TicketService.wsdl",
  targetNamespace="urn:TicketService", name="getInfo")
@XmlSeeAlso(
  { ObjectFactory.class })
@SOAPBinding(style=Style.RPC)
public interface GetInfo
{
  @WebMethod(action="urn:TicketService/getTransInfo")
  @Action(input="urn:TicketService/getTransInfo", output="urn:TicketService/getInfo/getTransInfoResponse")
  @WebResult(partName="payload", name="payload")
  public TransInfoResponse getTransInfo(@WebParam(partName="payload",
      name="payload")
    TransInfoRequest payload);

  @WebMethod(action="urn:TicketService/getTransInfo")
  @Action(input="urn:TicketService/getTransInfo", output="urn:TicketService/getInfo/getTransInfoXMLResponse")
  @WebResult(partName="payload", name="payload")
  public TransInfoXMLResponse getTransInfoXML(@WebParam(partName="payload",
      name="payload")
    TransInfoRequest payload);

  @WebMethod
  @Action(input="urn:TicketService/getInfo/requestRefundRequest", output="urn:TicketService/getInfo/requestRefundResponse")
  @WebResult(partName="payload", name="payload")
  public com.grigorio.rzd.TicketServiceWSProxy.RefundXMLResponse requestRefund(@WebParam(partName="payload",
      name="payload")
    com.grigorio.rzd.TicketServiceWSProxy.RefundRequest payload);
}
