.echo on
.open clients.db
insert into countries(val,name) values(248,"Абхазия");
insert into countries(val,name) values(1,"Австралия");
insert into countries(val,name) values(2,"Австрия");
insert into countries(val,name) values(3,"Азербайджан");
insert into countries(val,name) values(4,"Албания");
insert into countries(val,name) values(5,"Алжир");
insert into countries(val,name) values(155,"Американский Самоа");
insert into countries(val,name) values(156,"Ангилья");
insert into countries(val,name) values(6,"Ангола");
insert into countries(val,name) values(8,"Андорра");
insert into countries(val,name) values(157,"Антарктика");
insert into countries(val,name) values(13,"Антигуа и Барбуда");
insert into countries(val,name) values(158,"Антильские острова");
insert into countries(val,name) values(9,"Арабские Эмираты");
insert into countries(val,name) values(10,"Аргентина");
insert into countries(val,name) values(11,"Армения");
insert into countries(val,name) values(14,"Аруба");
insert into countries(val,name) values(12,"Афганистан");
insert into countries(val,name) values(15,"Багамские острова");
insert into countries(val,name) values(16,"Бангладеш");
insert into countries(val,name) values(17,"Барбадос");
insert into countries(val,name) values(18,"Бахрейн");
insert into countries(val,name) values(19,"Беларусь");
insert into countries(val,name) values(21,"Белиз");
insert into countries(val,name) values(20,"Бельгия");
insert into countries(val,name) values(22,"Бенин");
insert into countries(val,name) values(159,"Бермуды");
insert into countries(val,name) values(24,"Болгария");
insert into countries(val,name) values(25,"Боливия");
insert into countries(val,name) values(26,"Босния и Герцеговина");
insert into countries(val,name) values(27,"Ботсвана");
insert into countries(val,name) values(28,"Бразилия");
insert into countries(val,name) values(160,"Британские территории Индийского океана");
insert into countries(val,name) values(30,"Бруней");
insert into countries(val,name) values(29,"Буркина Фасо");
insert into countries(val,name) values(31,"Бурунди");
insert into countries(val,name) values(161,"Бутан");
insert into countries(val,name) values(162,"Вануату");
insert into countries(val,name) values(32,"Ватикан");
insert into countries(val,name) values(7,"Великобритания");
insert into countries(val,name) values(33,"Венгрия");
insert into countries(val,name) values(34,"Венесуэла");
insert into countries(val,name) values(163,"Виргинские острова (Британские)");
insert into countries(val,name) values(164,"Виргинские острова (США)");
insert into countries(val,name) values(165,"Восточный Тимор");
insert into countries(val,name) values(35,"Вьетнам");
insert into countries(val,name) values(36,"Габон");
insert into countries(val,name) values(37,"Гаити");
insert into countries(val,name) values(48,"Гайана");
insert into countries(val,name) values(38,"Гамбия");
insert into countries(val,name) values(39,"Гана");
insert into countries(val,name) values(166,"Гваделупа");
insert into countries(val,name) values(40,"Гватемала");
insert into countries(val,name) values(41,"Гвинея");
insert into countries(val,name) values(42,"Гвинея-Бисау");
insert into countries(val,name) values(43,"Германия");
insert into countries(val,name) values(167,"Гибралтар");
insert into countries(val,name) values(44,"Гондурас");
insert into countries(val,name) values(45,"Гонконг (Китай)");
insert into countries(val,name) values(168,"Гренада");
insert into countries(val,name) values(169,"Гренландия");
insert into countries(val,name) values(46,"Греция");
insert into countries(val,name) values(47,"Грузия");
insert into countries(val,name) values(170,"Гуам");
insert into countries(val,name) values(49,"Дания");
insert into countries(val,name) values(171,"Демократическая республика Конго");
insert into countries(val,name) values(172,"Джибути");
insert into countries(val,name) values(51,"Доминика");
insert into countries(val,name) values(50,"Доминиканская республика");
insert into countries(val,name) values(52,"Египет");
insert into countries(val,name) values(173,"ЕС");
insert into countries(val,name) values(53,"Замбия");
insert into countries(val,name) values(174,"Западная Сахара");
insert into countries(val,name) values(175,"Зимбабве");
insert into countries(val,name) values(54,"Израиль");
insert into countries(val,name) values(55,"Индия");
insert into countries(val,name) values(56,"Индонезия");
insert into countries(val,name) values(57,"Иордания");
insert into countries(val,name) values(58,"Ирак");
insert into countries(val,name) values(59,"Иран");
insert into countries(val,name) values(60,"Ирландия");
insert into countries(val,name) values(61,"Исландия");
insert into countries(val,name) values(62,"Испания");
insert into countries(val,name) values(63,"Италия");
insert into countries(val,name) values(64,"Йемен");
insert into countries(val,name) values(65,"Казахстан");
insert into countries(val,name) values(176,"Каймановы острова");
insert into countries(val,name) values(66,"Камбоджа");
insert into countries(val,name) values(67,"Камерун");
insert into countries(val,name) values(68,"Канада");
insert into countries(val,name) values(69,"Катар");
insert into countries(val,name) values(70,"Кения");
insert into countries(val,name) values(71,"Кипр");
insert into countries(val,name) values(177,"Кирибати");
insert into countries(val,name) values(73,"Китайская Народная Республика");
insert into countries(val,name) values(178,"Кокосовые острова");
insert into countries(val,name) values(74,"Колумбия");
insert into countries(val,name) values(179,"Коморские острова");
insert into countries(val,name) values(180,"Конго");
insert into countries(val,name) values(75,"Корейская Народная Демократическая республика");
insert into countries(val,name) values(151,"Корея");
insert into countries(val,name) values(77,"Коста Рика");
insert into countries(val,name) values(23,"Кот-д'Ивуар");
insert into countries(val,name) values(78,"Куба");
insert into countries(val,name) values(79,"Кувейт");
insert into countries(val,name) values(72,"Кыргызстан");
insert into countries(val,name) values(181,"Лаос");
insert into countries(val,name) values(80,"Латвия");
insert into countries(val,name) values(182,"Лесото");
insert into countries(val,name) values(81,"Либерия");
insert into countries(val,name) values(82,"Ливан");
insert into countries(val,name) values(183,"Ливия");
insert into countries(val,name) values(83,"Литва");
insert into countries(val,name) values(84,"Лихтенштейн");
insert into countries(val,name) values(85,"Люксембург");
insert into countries(val,name) values(184,"Маврикий");
insert into countries(val,name) values(185,"Мавритания");
insert into countries(val,name) values(186,"Мадагаскар");
insert into countries(val,name) values(187,"Майотта");
insert into countries(val,name) values(89,"Макао (Китай)");
insert into countries(val,name) values(86,"Македония");
insert into countries(val,name) values(92,"Малави");
insert into countries(val,name) values(87,"Малайзия");
insert into countries(val,name) values(93,"Мали");
insert into countries(val,name) values(188,"Мальдивские острова");
insert into countries(val,name) values(91,"Мальта");
insert into countries(val,name) values(189,"Марианские острова");
insert into countries(val,name) values(88,"Марокко");
insert into countries(val,name) values(190,"Мартиника");
insert into countries(val,name) values(191,"Маршалловы острова");
insert into countries(val,name) values(90,"Мексика");
insert into countries(val,name) values(192,"Микронезия");
insert into countries(val,name) values(94,"Мозамбик");
insert into countries(val,name) values(95,"Молдова");
insert into countries(val,name) values(96,"Монако");
insert into countries(val,name) values(97,"Монголия");
insert into countries(val,name) values(193,"Монтсеррат");
insert into countries(val,name) values(194,"Мьянма");
insert into countries(val,name) values(98,"Намибия");
insert into countries(val,name) values(195,"Науру");
insert into countries(val,name) values(99,"Непал");
insert into countries(val,name) values(100,"Нигер");
insert into countries(val,name) values(101,"Нигерия");
insert into countries(val,name) values(102,"Нидерланды");
insert into countries(val,name) values(103,"Никарагуа");
insert into countries(val,name) values(196,"Ниуэ");
insert into countries(val,name) values(104,"Новая Зеландия");
insert into countries(val,name) values(197,"Новая Каледония");
insert into countries(val,name) values(105,"Норвегия");
insert into countries(val,name) values(106,"Оман");
insert into countries(val,name) values(198,"ООН");
insert into countries(val,name) values(234,"остров Буве");
insert into countries(val,name) values(235,"остров Норфолк");
insert into countries(val,name) values(236,"остров Питкэрн");
insert into countries(val,name) values(237,"остров Рождества");
insert into countries(val,name) values(238,"остров Святой Елены");
insert into countries(val,name) values(239,"острова Валлис и Футуна");
insert into countries(val,name) values(240,"острова Герда и МакДональда");
insert into countries(val,name) values(241,"острова Зеленого Мыса");
insert into countries(val,name) values(242,"острова Кука");
insert into countries(val,name) values(243,"острова Самоа");
insert into countries(val,name) values(244,"острова Свалбард и Ян Майен");
insert into countries(val,name) values(245,"острова Туркс и Кайкос");
insert into countries(val,name) values(199,"Отдаленные Острова США");
insert into countries(val,name) values(107,"Пакистан");
insert into countries(val,name) values(200,"Палау");
insert into countries(val,name) values(201,"Палестина");
insert into countries(val,name) values(108,"Панама");
insert into countries(val,name) values(202,"Папуа - Новая Гвинея");
insert into countries(val,name) values(109,"Парагвай");
insert into countries(val,name) values(110,"Перу");
insert into countries(val,name) values(112,"Польша");
insert into countries(val,name) values(111,"Португалия");
insert into countries(val,name) values(113,"Пуэрто-Рико");
insert into countries(val,name) values(203,"Реюньон");
insert into countries(val,name) values(114,"Россия");
insert into countries(val,name) values(115,"Руанда");
insert into countries(val,name) values(116,"Румыния");
insert into countries(val,name) values(117,"Сальвадор");
insert into countries(val,name) values(118,"Сан-Марино");
insert into countries(val,name) values(204,"Сан-Томе и Принсипи");
insert into countries(val,name) values(119,"Саудовская Аравия");
insert into countries(val,name) values(205,"Свазиленд");
insert into countries(val,name) values(206,"Северная Ирландия");
insert into countries(val,name) values(207,"Сейшельские острова");
insert into countries(val,name) values(208,"Сен-Пьер и Микелон");
insert into countries(val,name) values(120,"Сенегал");
insert into countries(val,name) values(209,"Сент-Винсент и Гренадины");
insert into countries(val,name) values(210,"Сент-Китс и Невис");
insert into countries(val,name) values(211,"Сент-Люсия");
insert into countries(val,name) values(246,"Сербия");
insert into countries(val,name) values(121,"Сингапур");
insert into countries(val,name) values(122,"Сирия");
insert into countries(val,name) values(123,"Словакия");
insert into countries(val,name) values(124,"Словения");
insert into countries(val,name) values(125,"Соединенные Штаты Америки");
insert into countries(val,name) values(212,"Соломоновы острова");
insert into countries(val,name) values(213,"Сомали");
insert into countries(val,name) values(214,"Судан");
insert into countries(val,name) values(215,"Суринам");
insert into countries(val,name) values(126,"Сьерра-Леоне");
insert into countries(val,name) values(127,"Таджикистан");
insert into countries(val,name) values(129,"Тайвань (Республика Китай)");
insert into countries(val,name) values(128,"Тайланд");
insert into countries(val,name) values(130,"Танзания");
insert into countries(val,name) values(216,"Того");
insert into countries(val,name) values(217,"Токелау");
insert into countries(val,name) values(218,"Тонга");
insert into countries(val,name) values(219,"Тринидад и Тобаго");
insert into countries(val,name) values(220,"Тувалу");
insert into countries(val,name) values(131,"Тунис");
insert into countries(val,name) values(132,"Туркменистан");
insert into countries(val,name) values(133,"Турция");
insert into countries(val,name) values(134,"Уганда");
insert into countries(val,name) values(135,"Узбекистан");
insert into countries(val,name) values(136,"Украина");
insert into countries(val,name) values(137,"Уругвай");
insert into countries(val,name) values(221,"Уэльс");
insert into countries(val,name) values(222,"Фарерские острова");
insert into countries(val,name) values(138,"Фиджи");
insert into countries(val,name) values(139,"Филиппины");
insert into countries(val,name) values(140,"Финляндия");
insert into countries(val,name) values(223,"Фолклендские (Мальвинские) острова");
insert into countries(val,name) values(141,"Франция");
insert into countries(val,name) values(224,"Французская Гвиана");
insert into countries(val,name) values(225,"Французская Полинезия");
insert into countries(val,name) values(226,"Французские Южные Территории");
insert into countries(val,name) values(76,"Хорватия");
insert into countries(val,name) values(227,"Центральная Африканская Республика");
insert into countries(val,name) values(228,"Чад");
insert into countries(val,name) values(247,"Черногория");
insert into countries(val,name) values(142,"Чехия");
insert into countries(val,name) values(143,"Чили");
insert into countries(val,name) values(144,"Швейцария");
insert into countries(val,name) values(145,"Швеция");
insert into countries(val,name) values(229,"Шотландия");
insert into countries(val,name) values(146,"Шри Ланка");
insert into countries(val,name) values(147,"Эквадор");
insert into countries(val,name) values(230,"Экваториальная Гвинея");
insert into countries(val,name) values(231,"Эритрея");
insert into countries(val,name) values(148,"Эстония");
insert into countries(val,name) values(149,"Эфиопия");
insert into countries(val,name) values(152,"ЮАР");
insert into countries(val,name) values(150,"Югославия");
insert into countries(val,name) values(232,"Южная Георгия и Южные Сандвичевы острова");
insert into countries(val,name) values(153,"Ямайка");
insert into countries(val,name) values(154,"Япония");
